import 'dart:async';
import 'dart:io';

import 'package:flutter/services.dart';
import 'package:nextunnel_app/features/nextunnel/model/config_bundle.dart';
import 'package:nextunnel_app/utils/custom_loggers.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

/// Manages the bundled masterdns-client process — the "emergency mode" DNS
/// tunnel that survives total censorship (Iran-style blackout).
///
/// Lifecycle:
///   - extractIfNeeded(): unpack the platform binary from assets to a writable
///     dir on first run.
///   - writeConfig(entry): write client_config.toml + client_resolvers.txt
///     based on the per-server DnsTunnelEntry.
///   - start(): spawn the process; it opens a local SOCKS5 listener on port 18000.
///   - stop(): kills the process and clears state.
///
/// Failure mode is intentionally narrow: on macOS/Linux/Windows desktops only,
/// since iOS+Android can't spawn arbitrary binaries from app sandbox.
class DnsTunnelClientController with InfraLogger {
  Process? _process;
  String? _executablePath;
  String? _workDir;

  bool get isRunning => _process != null;

  /// Extract the masterdns-client binary from assets to a writable dir.
  /// Returns the path to the extracted executable.
  Future<String> extractIfNeeded() async {
    if (_executablePath != null) return _executablePath!;

    final platform = _platformKey();
    if (platform == null) {
      throw StateError("DNS tunnel client not supported on this platform");
    }

    final appSupport = await getApplicationSupportDirectory();
    final binDir = Directory(p.join(appSupport.path, "dnstun"));
    if (!binDir.existsSync()) binDir.createSync(recursive: true);

    final exeName = Platform.isWindows ? "masterdns-client.exe" : "masterdns-client";
    final exePath = p.join(binDir.path, exeName);
    final exeFile = File(exePath);

    final assetPath = "assets/binaries/$platform/$exeName";
    final byteData = await rootBundle.load(assetPath);
    await exeFile.writeAsBytes(byteData.buffer.asUint8List(byteData.offsetInBytes, byteData.lengthInBytes));

    if (!Platform.isWindows) {
      await Process.run("chmod", ["+x", exePath]);
    }

    _executablePath = exePath;
    _workDir = binDir.path;
    loggy.info("dnstun client extracted to $exePath");
    return exePath;
  }

  /// Write client_config.toml + client_resolvers.txt for the given entry.
  Future<void> writeConfig(DnsTunnelEntry entry) async {
    if (_workDir == null) {
      await extractIfNeeded();
    }
    final configPath = p.join(_workDir!, "client_config.toml");
    final resolversPath = p.join(_workDir!, "client_resolvers.txt");

    await File(configPath).writeAsString(_buildConfigToml(entry));
    await File(resolversPath).writeAsString(entry.resolvers.join("\n") + "\n");

    loggy.info("dnstun config written: domain=${entry.dnsDomain}, resolvers=${entry.resolvers.length}");
  }

  /// Start the masterdns-client process. Spawned as a managed child.
  Future<void> start({void Function(String line)? onLog}) async {
    if (_process != null) {
      throw StateError("dnstun client already running");
    }
    if (_executablePath == null || _workDir == null) {
      throw StateError("must call extractIfNeeded + writeConfig before start");
    }

    final proc = await Process.start(
      _executablePath!,
      ["--config", "client_config.toml", "--resolvers", "client_resolvers.txt"],
      workingDirectory: _workDir,
      mode: ProcessStartMode.normal,
    );

    _process = proc;
    proc.stdout.transform(const SystemEncoding().decoder).listen((line) {
      loggy.debug("[dnstun] $line");
      onLog?.call(line);
    });
    proc.stderr.transform(const SystemEncoding().decoder).listen((line) {
      loggy.warning("[dnstun:stderr] $line");
      onLog?.call(line);
    });
    proc.exitCode.then((code) {
      loggy.info("dnstun client exited with code $code");
      _process = null;
    });

    loggy.info("dnstun client started (pid ${proc.pid})");
  }

  Future<void> stop() async {
    final proc = _process;
    if (proc == null) return;
    proc.kill(ProcessSignal.sigterm);
    try {
      await proc.exitCode.timeout(const Duration(seconds: 5));
    } on TimeoutException {
      loggy.warning("dnstun did not exit gracefully — sending SIGKILL");
      proc.kill(ProcessSignal.sigkill);
    }
    _process = null;
  }

  String _buildConfigToml(DnsTunnelEntry entry) {
    return '''
# Auto-generated by nextunnel-app at ${DateTime.now().toIso8601String()}
DOMAINS = ["${entry.dnsDomain}"]
DATA_ENCRYPTION_METHOD = 5
ENCRYPTION_KEY = "${entry.encryptionKey}"

PROTOCOL_TYPE = "SOCKS5"
LISTEN_IP = "127.0.0.1"
LISTEN_PORT = 18000
SOCKS5_AUTH = false

LOCAL_DNS_ENABLED = false

RESOLVER_BALANCING_STRATEGY = 5
PACKET_DUPLICATION_COUNT = 3
SETUP_PACKET_DUPLICATION_COUNT = 4
RECHECK_INACTIVE_SERVERS_ENABLED = true
AUTO_DISABLE_TIMEOUT_SERVERS = true

UPLOAD_COMPRESSION_TYPE = 1
DOWNLOAD_COMPRESSION_TYPE = 1
COMPRESSION_MIN_SIZE = 120

MIN_UPLOAD_MTU = 38
MIN_DOWNLOAD_MTU = 200
MAX_UPLOAD_MTU = 150
MAX_DOWNLOAD_MTU = 4000

AUTO_REMOVE_LOW_MTU_SERVERS = true
MTU_TEST_RETRIES = 2
MTU_TEST_TIMEOUT = 2.0
MTU_TEST_PARALLELISM = 32

LOG_LEVEL = "INFO"
''';
  }

  String? _platformKey() {
    if (Platform.isLinux) return "linux-amd64";
    if (Platform.isWindows) return "windows-amd64";
    if (Platform.isMacOS) {
      // Process.run can detect arm64 vs amd64. Default to arm64 since modern
      // macs are Apple Silicon; users on Intel macs can manually override.
      return "macos-arm64";
    }
    return null;
  }
}
