app_id: 7M014649-53C2-5607-H580-CK880G32B76E
publisher: NexTunnel
publisher_url: https://github.com/ivaldepablo/nextunnel-app
display_name: NexTunnel
create_desktop_icon: true
install_dir_name: "{autopf64}\\NexTunnel"
setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - ar
  - en
  - es
  - fr
  - pt
  - ru
  - tr
script_template: inno_setup.sas
